
title: Jeffrey Herrera
email: jeff@kubonyc.com
description: > # this means to ignore newlines until "baseurl:"
  The portfolio of Jeffrey Herrera
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jeffreyherrera.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# Languages and syntax highlighting
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax-highlighter: rouge
theme: minima
# Gems
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-picture-tag
  - jemoji
  - jekyll-twitter-plugin
# For Travis CI and gulp
exclude: ["vendor",
          "_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json",
          "hologram_config.yml"]

# Work Collection
collections:
  work:
    output: true
    permalink: /:title/
defaults:
  - scope:
      path: ""
      type: work
    values:
      layout: page-project
      title: ""
      disciplines: ""
      permalink: ""
      order: ""
      work: true
